"""
Utilities: Parsers, Formatters, Validators, Helpers
"""

from pds_ultimate.utils.formatters import (
    SEPARATOR_BOLD,
    SEPARATOR_THIN,
    escape_markdown,
    format_brief,
    format_date,
    format_duration,
    format_error,
    format_header,
    format_key_value,
    format_list,
    format_money,
    format_order_summary,
    format_percentage,
    format_profit,
    format_relative_date,
    format_section,
    format_status,
    format_success,
    format_table,
    format_warning,
    truncate,
)
from pds_ultimate.utils.helpers import (
    AsyncTimer,
    Timer,
    async_retry,
    chunks,
    clamp,
    deduplicate,
    first_non_none,
    flatten,
    format_file_size,
    generate_id,
    generate_short_id,
    hash_file,
    hash_text,
    now_iso,
    quick_hash,
    retry_decorator,
    safe_float,
    safe_int,
    safe_json_dumps,
    safe_json_loads,
)
from pds_ultimate.utils.validators import (
    ValidationResult,
    detect_carrier,
    is_document,
    is_image,
    is_not_empty,
    is_safe_filename,
    is_valid_amount,
    is_valid_currency,
    is_valid_date,
    is_valid_email,
    is_valid_file_extension,
    is_valid_order_number,
    is_valid_phone,
    is_valid_tracking,
    is_voice,
    normalize_phone,
    parse_amount,
    parse_date,
    validate_file_size,
    validate_order_input,
    validate_text_length,
)

__all__ = [
    # Formatters
    "format_header", "format_section", "format_status",
    "format_success", "format_error", "format_warning",
    "format_money", "format_profit", "format_percentage",
    "format_date", "format_relative_date", "format_duration",
    "format_table", "format_list", "format_key_value",
    "format_order_summary", "format_brief",
    "truncate", "escape_markdown",
    "SEPARATOR_THIN", "SEPARATOR_BOLD",
    # Validators
    "is_valid_phone", "normalize_phone",
    "is_valid_email", "is_valid_currency", "is_valid_amount",
    "parse_amount", "is_valid_date", "parse_date",
    "is_valid_tracking", "detect_carrier",
    "is_valid_file_extension", "is_document", "is_image", "is_voice",
    "validate_file_size", "is_not_empty", "validate_text_length",
    "is_safe_filename", "is_valid_order_number",
    "validate_order_input", "ValidationResult",
    # Helpers
    "generate_id", "generate_short_id",
    "hash_text", "hash_file", "quick_hash",
    "format_file_size",
    "async_retry", "retry_decorator",
    "chunks",
    "safe_json_loads", "safe_json_dumps",
    "Timer", "AsyncTimer",
    "clamp", "first_non_none", "now_iso",
    "safe_int", "safe_float",
    "flatten", "deduplicate",
]
